version: '3.7'

services:
  reverseproxy:
    build:
      context: .
    image: frodotus/nginx-reverse-proxy:latest
    ports:
      - 8123:8123
    environment:
      - LISTEN_PORT=8123
      - PROXY_PASS=http://test-web
    depends_on:
        - test-web

  test-web:
        image: nginx:alpine
